stonks/eightpillars/urls.py
from django.urls import re_path

from django.contrib.auth import views as auth_views

from . import views

app_name = "eightpillars"

urlpatterns = [
    re_path(r'^$', views.HomePage.as_view(), name="homepage"),
    re_path(r'^view_all_eight_pillar_data$', views.view_all_eight_pillar_data, name="view_all_eight_pillar_data"),
    re_path(r'^view_all_eight_pillar_winner_data$', views.view_all_eight_pillar_winner_data, name="view_all_eight_pillar_winner_data"),

    re_path(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    #Functions
    re_path(r'^get_the_pillars', views.get_the_pillars, name='get_the_pillars'),
    re_path(r'^get_the_pillar_table', views.get_the_pillar_table, name='get_the_pillar_table'),    
]

stonks/stonks/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eightpillars/', include('eightpillars.urls')),
]

stonks/eightpillars/models.py
from django.db import models
from djmoney.models.fields import MoneyField
class EightPillarData(models.Model):
    ticker = models.CharField(max_length=10, null=False)
    company_name = models.CharField(max_length=100, null=True)
    market_cap = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    Eps = models.IntegerField(null=True)
    Pe = models.IntegerField(null=True)
    is_pe_acceptable = models.BooleanField(null=True)
    profit_margin = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    is_profit_margin_acceptable = models.BooleanField(null=True)
    latest_revenue = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    earliest_revenue = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_revenue_growing = models.BooleanField(null=True)
    latest_net_income = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    earliest_net_income = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_net_income_growing = models.BooleanField(null=True)
    latest_shares_outstanding = models.IntegerField(null=True)
    earliest_shares_outstanding = models.IntegerField(null=True)
    shares_outstanding = models.IntegerField(null=True)
    are_shares_outstanding_shrinking = models.BooleanField(null=True)
    quick_ratio = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    is_quick_ratio_positive = models.BooleanField(null=True)
    latest_free_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    earliest_free_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_cash_flow_growing = models.BooleanField(null=True)
    average_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_dividend_yield_affordable = models.BooleanField(null=True)
    cash_flow_value = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_market_price_worth = models.BooleanField(null=True)
    last_updated = models.DateTimeField(auto_now=True, null=False)
    
    def __str__(self):
        return self.company_name
class failedTickers(models.Model):
    ticker = models.CharField(max_length=10, null=False)
    errorDesc = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.ticker

stonks/eightpillars/forms.py
from django import forms

class TickerForm(forms.Form):
    ticker = forms.CharField(max_length=10)
    

    

stonks/eightpillars/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings
from django.db.models import Sum
from django.utils import timezone
from collections import defaultdict

from .forms import TickerForm

from .models import EightPillarData

import yfinance as yf
import yahoo_fin.stock_info as si
import pandas as pd
import requests
import json
from lxml import etree 

class HomePage(generic.TemplateView):
    template_name = 'eightpillars/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickerform'] = TickerForm()
        return context

def view_all_eight_pillar_winner_data(request):
    data ={}
    try:
        data['eightpillardata'] = EightPillarData.objects.filter(
            is_pe_acceptable = True,
            is_profit_margin_acceptable = True,
            is_revenue_growing = True,
            is_net_income_growing = True,
            are_shares_outstanding_shrinking = True,
            is_quick_ratio_positive = True,
            is_cash_flow_growing = True,
            is_dividend_yield_affordable = True,
            is_market_price_worth = True
        )
    except:
        data['message'] = 'There was an error'
    return render(request, 'eightpillars/includes/all8pillartable.html', data)

def view_all_eight_pillar_data(request):
    data ={}
    try:
        data['eightpillardata'] = EightPillarData.objects.all()
    except:
        data['message'] = 'There was an error'
    return render(request, 'eightpillars/includes/all8pillartable.html', data)

def get_the_pillars(request):
    data = {}
    status = 200
    if request.method == 'GET':
        tickerSymbol = request.GET.get('tickerSymbol').upper()
        quoteTbl = si.get_quote_table(tickerSymbol)
        income_statement = si.get_income_statement(tickerSymbol)
        balance_sheet = si.get_balance_sheet(tickerSymbol)
        cash_flow_statement = si.get_cash_flow(tickerSymbol)
        yf_data = yf.Ticker(tickerSymbol)
        company_name = yf_data.info['longName']
        currPrice = quoteTbl["Quote Price"]

        sharesOutstanding = yf_data.info['sharesOutstanding'] 
        market_cap = yf_data.info['marketCap'] 

        #EPS missing                                                                
        #                                                                           Formula: (Net Income - Preferred Dividends) / Shares Outstanding
        #Using Trailing (past performance) EPS
        Eps = quoteTbl["EPS (TTM)"]

        #PE Ratio missing                                                           
        #                                                                           Formula: Price / EPS
        #Using Trailing (past performance) PE
        Pe = quoteTbl["PE Ratio (TTM)"]

        #determine what a good profit margin is
        profit_margin = yf_data.info['profitMargins']
        is_profit_margin_good = profit_margin > .1
        dividendYield = yf_data.info['dividendYield'] 
        #                                                                           Formula: (Price * Shares Outstanding) * dividend yield
        dividendsPaid = (currPrice * sharesOutstanding) * dividendYield if dividendYield else None #Ensure the dividends paid is supported by free cash flow

        #4 year income statement comparison

        #Revenue
        latest_revenue = income_statement[income_statement.columns[0]][income_statement.index.get_loc('totalRevenue')] if 'totalRevenue' in income_statement.index else None
        earliest_revenue = income_statement[income_statement.columns[3]][income_statement.index.get_loc('totalRevenue')] if 'totalRevenue' in income_statement.index else None
        is_revenue_growing = latest_revenue > earliest_revenue

        #Net Income
        latest_net_income = income_statement[income_statement.columns[0]][income_statement.index.get_loc('netIncomeFromContinuingOps')] if 'netIncomeFromContinuingOps' in income_statement.index else None  
        earliest_net_income = income_statement[income_statement.columns[3]][income_statement.index.get_loc('netIncomeFromContinuingOps')] if 'netIncomeFromContinuingOps' in income_statement.index else None
        is_net_income_growing = latest_net_income > earliest_net_income

        #Shares Outstanding
        try:
            headers = {'User-agent': 'Mozilla/5.0'}
            html = requests.get(url='https://finance.yahoo.com/quote/'+tickerSymbol+'/balance-sheet?p='+tickerSymbol, headers=headers).text
            json_str = html.split('root.App.main =')[1].split(
                '(this)')[0].split(';\n}')[0].strip()
            json_data = json.loads(json_str)        
            latest_shares_outstanding = json_data['context']['dispatcher']['stores']['QuoteTimeSeriesStore']['timeSeries']['annualShareIssued'][3]['reportedValue']['raw']  
            earliest_shares_outstanding = json_data['context']['dispatcher']['stores']['QuoteTimeSeriesStore']['timeSeries']['annualShareIssued'][0]['reportedValue']['raw']  
        except:
            latest_shares_outstanding = None
            earliest_shares_outstanding = None
            
        #Current Assets over Current Liabilities
        current_assets = balance_sheet[balance_sheet.columns[0]][balance_sheet.index.get_loc('totalCurrentAssets')] if 'totalCurrentAssets' in balance_sheet.index else None 
        current_liabilities = balance_sheet[balance_sheet.columns[0]][balance_sheet.index.get_loc('totalCurrentLiabilities')] if 'totalCurrentAssets' in balance_sheet.index else None 
        is_quick_ratio_positive = (current_assets / current_liabilities) > 1

        try:
            #Free Cash Flow
            #                                                                                       Formula: Cash from Operations - Net Change in Capital Expenditures
            latest_cash_from_operations = cash_flow_statement[cash_flow_statement.columns[0]][cash_flow_statement.index.get_loc('totalCashFromOperatingActivities')] if 'totalCashFromOperatingActivities' in cash_flow_statement.index else 0
            latest_capital_expenditures = cash_flow_statement[cash_flow_statement.columns[0]][cash_flow_statement.index.get_loc('capitalExpenditures')] if 'capitalExpenditures' in cash_flow_statement.index else 0
            latest_free_cash_flow = latest_cash_from_operations + latest_capital_expenditures
            earliest_cash_from_operations = cash_flow_statement[cash_flow_statement.columns[3]][cash_flow_statement.index.get_loc('totalCashFromOperatingActivities')] if 'totalCashFromOperatingActivities' in cash_flow_statement.index else 0
            earliest_capital_expenditures = cash_flow_statement[cash_flow_statement.columns[3]][cash_flow_statement.index.get_loc('capitalExpenditures')] if 'capitalExpenditures' in cash_flow_statement.index else 0
            earliest_free_cash_flow = earliest_cash_from_operations + earliest_capital_expenditures


            free_cash_flow = 0
            for i in range(0, 4):
                cash_from_operations = cash_flow_statement[cash_flow_statement.columns[i]][cash_flow_statement.index.get_loc('totalCashFromOperatingActivities')] if 'totalCashFromOperatingActivities' in cash_flow_statement.index else 0
                capital_expenditures = cash_flow_statement[cash_flow_statement.columns[i]][cash_flow_statement.index.get_loc('capitalExpenditures')] if 'capitalExpenditures' in cash_flow_statement.index else 0
                free_cash_flow += (cash_from_operations + capital_expenditures)
            average_cash_flow = free_cash_flow/4
            cash_flow_minus_dividend = average_cash_flow - dividendsPaid if dividendsPaid else average_cash_flow
            cash_flow_value = average_cash_flow * 20
        except:
            latest_free_cash_flow = None
            earliest_free_cash_flow = None
            average_cash_flow = None
            cash_flow_minus_dividend = None
            cash_flow_value = None

        data['ticker'] = tickerSymbol
        data['company_name'] = company_name
        data['market_cap'] = market_cap
        data['Eps'] = int(Eps) if pd.notnull(Eps) else int(0)
        data['Pe'] = int(Pe) if pd.notnull(Pe) else int(0)
        data['is_pe_acceptable'] = bool(Pe < 20) if pd.notnull(Pe) and Pe != 0 else False
        data['profit_margin'] = '{0:.3%}'.format(profit_margin)
        data['is_profit_margin_acceptable'] = bool(profit_margin > .1)
        data['latest_revenue'] = int(latest_revenue)
        data['earliest_revenue'] = int(earliest_revenue)
        data['is_revenue_growing'] = bool(latest_revenue > earliest_revenue)
        data['latest_net_income'] = int(latest_net_income)
        data['earliest_net_income'] = int(earliest_net_income)
        data['is_net_income_growing'] = bool(latest_net_income > earliest_net_income)
        data['earliest_shares_outstanding'] = int(earliest_shares_outstanding) if earliest_shares_outstanding else None
        data['latest_shares_outstanding'] = int(latest_shares_outstanding) if latest_shares_outstanding else None
        data['shares_outstanding'] = int(sharesOutstanding)
        data['are_shares_outstanding_shrinking'] = bool(latest_shares_outstanding < earliest_shares_outstanding) if latest_shares_outstanding and earliest_shares_outstanding else None
        data['quick_ratio'] = (current_assets / current_liabilities)
        data['is_quick_ratio_positive'] = bool((current_assets / current_liabilities) > 1)
        data['latest_free_cash_flow'] = int(latest_free_cash_flow) if latest_free_cash_flow else None
        data['earliest_free_cash_flow'] = int(earliest_free_cash_flow) if earliest_free_cash_flow else None

stonks/templates/eightpillars/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>STOCK VIEW</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/eightpillars/home.css' %}">
        <script type="text/javascript" src="{% static "js/jquery-3.5.1.min.js" %}"></script>
    </head>
    
    <body>
        <nav>
            <div class="container nav-wrapper">
                <img class="logo" src="{% static 'images/eightpillars/logo.png' %}" />
                <a href="/" class="headername">STOCK VIEW</a>
                <ul id="nav-mobile" class="right">
                    <li><a href="{% url 'eightpillars:homepage' %}">Home</a></li>
                    <li><a href="{% url 'eightpillars:view_all_eight_pillar_winner_data' %}">VIEW WINNERS</a></li>
                    <li><a href="{% url 'eightpillars:view_all_eight_pillar_data' %}">VIEW ALL</a></li>
                    <li><a href="#">Logout<a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

stonks/templates/eightpillars/homepage.html
{% load humanize %}
<div class="row" id='shortRatioDiv'>
    <table class="highlight responsive-table black-text" id="stocktbl">
        <tr>
            <th onclick="sortTable(0);">Stock Name (Equity: ${{equity|intcomma}})</th>
            <th onclick="sortTable(1);">Position</th>
            <th onclick="sortTable(2);">Quantity ({{qty_total}})</th>
            <th onclick="sortTable(3);">Current Price</th>
            <th onclick="sortTable(4);">Gain/Loss ({{delta}})</th>
        </tr>
        {% for stock_data, values in stocks.items %}
          {% for stock, value in values.items %}
          <tr class="{% if value.previousClose > value.Current_Price %}red lighten-2{% elif value.Current_Price > value.previousClose %}green lighten-2{% endif %}">
              <td>{{stock}} ({{value.equity|intcomma}})</td>
              <td>{{value.position}}</td>
              <td>{{value.qty}}</td>
              <td>{{value.Current_Price|intcomma}}({{value.perc_change}})</td>
              <td class="{% if value.position > value.Current_Price %}red{% else %}green{% endif %}">{{value.totaldiff|intcomma}}
          </tr>
          {% endfor %}
        {% endfor %}
    </table>
</div>
<script>
window.onload=function(e){
    sortTable(1);     
}
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("stocktbl");
  switching = true;
  // Set the sorting direction to ascending:
  dir = "asc";
  /* Make a loop that will continue until
  no switching has been done: */
  while (switching) {
    // Start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /* Loop through all table rows (except the
    first, which contains table headers): */
    for (i = 1; i < (rows.length - 1); i++) {
      // Start by saying there should be no switching:
      shouldSwitch = false;
      /* Get the two elements you want to compare,
      one from current row and one from the next: */
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /* Check if the two rows should switch place,
      based on the direction, asc or desc: */
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /* If a switch has been marked, make the switch
      and mark that a switch has been done: */
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      // Each time a switch is done, increase this count by 1:
      switchcount ++;
    } else {
      /* If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again. */
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
</script>

stonks/templates/eightpillars/index.html
{% extends 'eightpillars/base.html' %}

{% block content %}
<div id="mainview">
    {% include 'eightpillars/includes/8pillaranalysis.html' %}
</div>

{% endblock %}