stonks/eightpillars/urls.py
from django.urls import re_path

from django.contrib.auth import views as auth_views

from . import views

app_name = "eightpillars"

urlpatterns = [
    re_path(r'^$', views.HomePage.as_view(), name="homepage"),
    re_path(r'^view_all_eight_pillar_data$', views.view_all_eight_pillar_data, name="view_all_eight_pillar_data"),
    re_path(r'^view_all_eight_pillar_winner_data$', views.view_all_eight_pillar_winner_data, name="view_all_eight_pillar_winner_data"),

    re_path(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    #Functions
    re_path(r'^get_the_pillars', views.get_the_pillars, name='get_the_pillars'),
    re_path(r'^get_the_pillar_table', views.get_the_pillar_table, name='get_the_pillar_table'),    
]

stonks/stonks/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eightpillars/', include('eightpillars.urls')),
]

stonks/eightpillars/models.py
from django.db import models
from djmoney.models.fields import MoneyField
class EightPillarData(models.Model):
    ticker = models.CharField(max_length=10, null=False)
    company_name = models.CharField(max_length=100, null=True)
    market_cap = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    Eps = models.IntegerField(null=True)
    Pe = models.IntegerField(null=True)
    is_pe_acceptable = models.BooleanField(null=True)
    profit_margin = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    is_profit_margin_acceptable = models.BooleanField(null=True)
    latest_revenue = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    earliest_revenue = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_revenue_growing = models.BooleanField(null=True)
    latest_net_income = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    earliest_net_income = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_net_income_growing = models.BooleanField(null=True)
    latest_shares_outstanding = models.IntegerField(null=True)
    earliest_shares_outstanding = models.IntegerField(null=True)
    shares_outstanding = models.IntegerField(null=True)
    are_shares_outstanding_shrinking = models.BooleanField(null=True)
    quick_ratio = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    is_quick_ratio_positive = models.BooleanField(null=True)
    latest_free_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    earliest_free_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_cash_flow_growing = models.BooleanField(null=True)
    average_cash_flow = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_dividend_yield_affordable = models.BooleanField(null=True)
    cash_flow_value = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', null=True)
    is_market_price_worth = models.BooleanField(null=True)
    last_updated = models.DateTimeField(auto_now=True, null=False)
    
    def __str__(self):
        return self.company_name
class failedTickers(models.Model):
    ticker = models.CharField(max_length=10, null=False)
    errorDesc = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.ticker

stonks/eightpillars/forms.py
from django import forms

class TickerForm(forms.Form):
    ticker = forms.CharField(max_length=10)
    

    

stonks/eightpillars/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings
from django.db.models import Sum
from django.utils import timezone
from collections import defaultdict

from .forms import TickerForm

from .models import EightPillarData

import yfinance as yf
import yahoo_fin.stock_info as si
import pandas as pd
import requests
import json
from lxml import etree 

class HomePage(generic.TemplateView):
    template_name = 'eightpillars/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickerform'] = TickerForm()
        return context

def view_all_eight_pillar_winner_data(request):
    data ={}
    try:
        data['eightpillardata'] = EightPillarData.objects.filter(
            is_pe_acceptable = True,
            is_profit_margin_acceptable = True,
            is_revenue_growing = True,
            is_net_income_growing = True,
            are_shares_outstanding_shrinking = True,
            is_quick_ratio_positive = True,
            is_cash_flow_growing = True,
            is_dividend_yield_affordable = True,
            is_market_price_worth = True
        )
    except:
        data['message'] = 'There was an error'
    return render(request, 'eightpillars/includes/all8pillartable.html', data)

def view_all_eight_pillar_data(request):
    data ={}
    try:
        data['eightpillardata'] = EightPillarData.objects.all()
    except:
        data['message'] = 'There was an error'
    return render(request, 'eightpillars/includes/all8pillartable.html', data)

def get_the_pillars(request):
    data = {}
    status = 200
    if request.method == 'GET':
        tickerSymbol = request.GET.get('tickerSymbol').upper()
        quoteTbl = si.get_quote_table(tickerSymbol)
        income_statement = si.get_income_statement(tickerSymbol)
        balance_sheet = si.get_balance_sheet(tickerSymbol)
        cash_flow_statement = si.get_cash_flow(tickerSymbol)
        yf_data = yf.Ticker(tickerSymbol)
        company_name = yf_data.info['longName']
        currPrice = quoteTbl["Quote Price"]

        sharesOutstanding = yf_data.info['sharesOutstanding'] 
        market_cap = yf_data.info['marketCap'] 

        #EPS missing                                                                
        #                                                                           Formula: (Net Income - Preferred Dividends) / Shares Outstanding
        #Using Trailing (past performance) EPS
        Eps = quoteTbl["EPS (TTM)"]

        #PE Ratio missing                                                           
        #                                                                           Formula: Price / EPS
        #Using Trailing (past performance) PE
        Pe = quoteTbl["PE Ratio (TTM)"]

        #determine what a good profit margin is
        profit_margin = yf_data.info['profitMargins']
        is_profit_margin_good = profit_margin > .1
        dividendYield = yf_data.info['dividendYield'] 
        #                                                                           Formula: (Price * Shares Outstanding) * dividend yield
        dividendsPaid = (currPrice * sharesOutstanding) * dividendYield if dividendYield else None #Ensure the dividends paid is supported by free cash flow

        #4 year income statement comparison

        #Revenue
        latest_revenue = income_statement[income_statement.columns[0]][income_statement.index.get_loc('totalRevenue')] if 'totalRevenue' in income_statement.index else None
        earliest_revenue = income_statement[income_statement.columns[3]][income_statement.index.get_loc('totalRevenue')] if 'totalRevenue' in income_statement.index else None
        is_revenue_growing = latest_revenue > earliest_revenue

        #Net Income
        latest_net_income = income_statement[income_statement.columns[0]][income_statement.index.get_loc('netIncomeFromContinuingOps')] if 'netIncomeFromContinuingOps' in income_statement.index else None  
        earliest_net_income = income_statement[income_statement.columns[3]][income_statement.index.get_loc('netIncomeFromContinuingOps')] if 'netIncomeFromContinuingOps' in income_statement.index else None
        is_net_income_growing = latest_net_income > earliest_net_income

        #Shares Outstanding
        try:
            headers = {'User-agent': 'Mozilla/5.0'}
            html = requests.get(url='https://finance.yahoo.com/quote/'+tickerSymbol+'/balance-sheet?p='+tickerSymbol, headers=headers).text
            json_str = html.split('root.App.main =')[1].split(
                '(this)')[0].split(';\n}')[0].strip()
            json_data = json.loads(json_str)        
            latest_shares_outstanding = json_data['context']['dispatcher']['stores']['QuoteTimeSeriesStore']['timeSeries']['annualShareIssued'][3]['reportedValue']['raw']  
            earliest_shares_outstanding = json_data['context']['dispatcher']['stores']['QuoteTimeSeriesStore']['timeSeries']['annualShareIssued'][0]['reportedValue']['raw']  
        except:
            latest_shares_outstanding = None
            earliest_shares_outstanding = None
            
        #Current Assets over Current Liabilities
        current_assets = balance_sheet[balance_sheet.columns[0]][balance_sheet.index.get_loc('totalCurrentAssets')] if 'totalCurrentAssets' in balance_sheet.index else None 
        current_liabilities = balance_sheet[balance_sheet.columns[0]][balance_sheet.index.get_loc('totalCurrentLiabilities')] if 'totalCurrentAssets' in balance_sheet.index else None 
        is_quick_ratio_positive = (current_assets / current_liabilities) > 1

        try:
            #Free Cash Flow
            #                                                                                       Formula: Cash from Operations - Net Change in Capital Expenditures
            latest_cash_from_operations = cash_flow_statement[cash_flow_statement.columns[0]][cash_flow_statement.index.get_loc('totalCashFromOperatingActivities')] if 'totalCashFromOperatingActivities' in cash_flow_statement.index else 0
            latest_capital_expenditures = cash_flow_statement[cash_flow_statement.columns[0]][cash_flow_statement.index.get_loc('capitalExpenditures')] if 'capitalExpenditures' in cash_flow_statement.index else 0
            latest_free_cash_flow = latest_cash_from_operations + latest_capital_expenditures
            earliest_cash_from_operations = cash_flow_statement[cash_flow_statement.columns[3]][cash_flow_statement.index.get_loc('totalCashFromOperatingActivities')] if 'totalCashFromOperatingActivities' in cash_flow_statement.index else 0
            earliest_capital_expenditures = cash_flow_statement[cash_flow_statement.columns[3]][cash_flow_statement.index.get_loc('capitalExpenditures')] if 'capitalExpenditures' in cash_flow_statement.index else 0
            earliest_free_cash_flow = earliest_cash_from_operations + earliest_capital_expenditures


            free_cash_flow = 0
            for i in range(0, 4):
                cash_from_operations = cash_flow_statement[cash_flow_statement.columns[i]][cash_flow_statement.index.get_loc('totalCashFromOperatingActivities')] if 'totalCashFromOperatingActivities' in cash_flow_statement.index else 0
                capital_expenditures = cash_flow_statement[cash_flow_statement.columns[i]][cash_flow_statement.index.get_loc('capitalExpenditures')] if 'capitalExpenditures' in cash_flow_statement.index else 0
                free_cash_flow += (cash_from_operations + capital_expenditures)
            average_cash_flow = free_cash_flow/4
            cash_flow_minus_dividend = average_cash_flow - dividendsPaid if dividendsPaid else average_cash_flow
            cash_flow_value = average_cash_flow * 20
        except:
            latest_free_cash_flow = None
            earliest_free_cash_flow = None
            average_cash_flow = None
            cash_flow_minus_dividend = None
            cash_flow_value = None

        data['ticker'] = tickerSymbol
        data['company_name'] = company_name
        data['market_cap'] = market_cap
        data['Eps'] = int(Eps) if pd.notnull(Eps) else int(0)
        data['Pe'] = int(Pe) if pd.notnull(Pe) else int(0)
        data['is_pe_acceptable'] = bool(Pe < 20) if pd.notnull(Pe) and Pe != 0 else False
        data['profit_margin'] = '{0:.3%}'.format(profit_margin)
        data['is_profit_margin_acceptable'] = bool(profit_margin > .1)
        data['latest_revenue'] = int(latest_revenue)
        data['earliest_revenue'] = int(earliest_revenue)
        data['is_revenue_growing'] = bool(latest_revenue > earliest_revenue)
        data['latest_net_income'] = int(latest_net_income)
        data['earliest_net_income'] = int(earliest_net_income)
        data['is_net_income_growing'] = bool(latest_net_income > earliest_net_income)
        data['earliest_shares_outstanding'] = int(earliest_shares_outstanding) if earliest_shares_outstanding else None
        data['latest_shares_outstanding'] = int(latest_shares_outstanding) if latest_shares_outstanding else None
        data['shares_outstanding'] = int(sharesOutstanding)
        data['are_shares_outstanding_shrinking'] = bool(latest_shares_outstanding < earliest_shares_outstanding) if latest_shares_outstanding and earliest_shares_outstanding else None
        data['quick_ratio'] = (current_assets / current_liabilities)
        data['is_quick_ratio_positive'] = bool((current_assets / current_liabilities) > 1)
        data['latest_free_cash_flow'] = int(latest_free_cash_flow) if latest_free_cash_flow else None
        data['earliest_free_cash_flow'] = int(earliest_free_cash_flow) if earliest_free_cash_flow else None

stonks/templates/eightpillars/includes/8pillaranalysis.html
<div id="tickerformdiv">
    {{tickerform.as_p}}
    <button id="tickerBTN" onclick="getThePillars(event);" class="btn waves-effect waves-light" type="submit" name="action">Get Pillar Data
        <i class="material-icons right">send</i>
    </button>
    <div id="8pillardiv">

    </div>
</div>
<script>
    $("#id_ticker").keyup(function(event) {
        if (event.keyCode === 13) {
            $("#tickerBTN").click();
        }
    });
    function getThePillars(event) {
        event.preventDefault();
        if($('#id_ticker').val() == ''){
            alert('Enter a Ticker');
            $('#id_ticker').focus();
            return
        }
        $('#8pillardiv').html('Loading....');
        $.ajax({
            url: '{% url "eightpillars:get_the_pillar_table" %}',
            data: {
                tickerSymbol: $('#id_ticker').val()
            },
            timeout: 120000,
            success: function (data) {
                $('#8pillardiv').html(data);
            },
            error: function(){
                $('#8pillardiv').html("There was an error getting data.");
            }
        });
    };
</script>

stonks/templates/eightpillars/includes/all8pillartable.html
{% extends 'eightpillars/base.html' %}
{% load humanize %}
{% load formatit %}

{% block content %}
<div id="mainview">
    {% if eightpillardata %}
        <div style="left:0; position:absolute;">
            <fieldset><legend>FILTER</legend>
            <p><label for="peck"><input type="checkbox" id="peck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">PE</span></label> </p>
            <p><label for="pmck"><input type="checkbox" id="pmck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">PROFIT MARGIN</span></label> </p>
            <p><label for="revck"><input type="checkbox" id="revck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">REVENUE GROWTH</span></label> </p>
            <p><label for="prock"><input type="checkbox" id="prock" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">PROFIT GROWTH</span></label> </p>
            <p><label for="shck"><input type="checkbox" id="shck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">SHARES OUTSTANDING</span></label> </p>
            <p><label for="quck"><input type="checkbox" id="quck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">QUICK RATIO</span></label> </p>
            <p><label for="fcfck"><input type="checkbox" id="fcfck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">FREE CASH FLOW</span></label> </p>
            <p><label for="afcfck"><input type="checkbox" id="afcfck" class="filled-in" style="display:none;" /><span class="blue-text text-darken-2">AFCFV VS MARKET CAP</span></label>
            </fieldset>
        </div>
        <div id="countdiv">
        </div>
        {% for obj in eightpillardata %}
            <table style="border: 2px solid black; display:block;" 
                class="
                    {% if obj.is_pe_acceptable %}
                    peck 
                    {% endif %}
                    {% if obj.are_shares_outstanding_shrinking %}
                    shck 
                    {% endif %}
                    {% if obj.is_profit_margin_acceptable %}
                    pmck 
                    {% endif %}
                    {% if obj.is_quick_ratio_positive %}
                    quck 
                    {% endif %}
                    {% if obj.is_revenue_growing %}
                    revck 
                    {% endif %}
                    {% if obj.is_cash_flow_growing %}
                    fcfck 
                    {% endif %}
                    {% if obj.is_net_income_growing %}
                    prock 
                    {% endif %}
                    {% if obj.is_market_price_worth %}
                    afcfck 
                    {% endif %}
                "
            >
                <tr>
                    <th colspan=6><a href="https://www.tradingview.com/chart/?symbol={{obj.ticker}}"  target="_blank" rel="noopener noreferrer">Company: {{obj.company_name}} ({{obj.ticker}}) <i style="font-size: 10px;">last updated: {{obj.last_updated}}</i></a></th>
                </tr>
                <tr>
                    <th>PE (<20)</th>
                    <td>{{obj.Pe}}</td>
                    <td>{% if obj.is_pe_acceptable %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}           
                    <th>Shares Outstanding Reduced</th>
                    <td>Current: {{obj.shares_outstanding|intcomma}} 4 years ago: {{obj.earliest_shares_outstanding|intcomma}}</td>
                    <td>{% if obj.are_shares_outstanding_shrinking %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}           
                </tr>
                <tr>
                    <th>Profit Margin > 10%</th>
                    <td>{{obj.profit_margin|to_percent:0}}</td>
                    <td>{% if obj.is_profit_margin_acceptable %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}</td>
                    <th>Quick Ratio</th>
                    <td>{{obj.quick_ratio|to_percent:0}}</td>
                    <td>{% if obj.is_quick_ratio_positive %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}        
                </tr>
                <tr>
                    <th>Revenue Growth (4 years)</th>
                    <td>Current: {{obj.latest_revenue|intcomma}} 4 years ago: {{obj.earliest_revenue|intcomma}}</td>
                    <td>{% if obj.is_revenue_growing %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}           
                    <th>Free Cash Flow</th>
                    <td>
                        Current: {{obj.latest_free_cash_flow|intcomma}} 
                        4 years ago: {{obj.earliest_free_cash_flow|intcomma}} 
                        <br /> 
                        4 year avg: {{obj.average_cash_flow|intcomma}}                    
                    </td>    
                    <td>{% if obj.is_cash_flow_growing %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}               
                </tr>
                <tr>
                    <th>Profit Growth (4 years)</th>
                    <td>Current: {{obj.latest_net_income|intcomma}} 4 years ago: {{obj.earliest_net_income|intcomma}}</td>        
                    <td>{% if obj.is_net_income_growing %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}           
                    <th>4 year Average Free Cash Flow * 20 <br />compared to Market Cap</th>
                    <td>AFCF Value: {{obj.cash_flow_value|intcomma}} <br /> vs Market Cap: {{obj.market_cap|intcomma}}</td>     
                    <td>{% if obj.is_market_price_worth %}<i class="material-icons dp48">check_circle</i>{% else %}<i class="material-icons dp48">clear</i>{% endif %}                
                </tr>  
            </table>
        {% endfor %}
        <script>
            $(document).ready(function(){
                $("#countdiv").html("Results: "+countResults());
            })
            var checkboxes = document.querySelectorAll("input[type=checkbox]");
            checkboxes.forEach(function(checkbox) {
                checkbox.addEventListener('change', function() {
                    if (checkifallunchecked()){
                        //if none are checked unhide all
                        document.querySelectorAll('table').forEach(function(tbls){
                            tbls.style.display = 'block';
                        });      
                        $("#countdiv").html("Results: "+countResults());
                    } else {
                        //check which ones are checked
                        clsChecked = new Array();
                        clsChecked = checkwhicharechecked();
                        //hide all tables
                        document.querySelectorAll('table').forEach(function(tbls){
                            tbls.style.display = 'none';
                        });
                        //reveal checked ones
                        document.querySelectorAll("."+clsChecked.join('.')).forEach(function(tblChecked){
                            tblChecked.style.display = 'block';
                        });
                        $("#countdiv").html("Results: "+countResults());
                    }
                })
            });     
            function checkwhicharechecked(){
                var clsArr = new Array();
                var checkboxes = document.querySelectorAll("input[type=checkbox]");
                checkboxes.forEach(function(checkbox) {
                    if (checkbox.checked) {
                        clsArr.push(checkbox.id);
                    }
                })
                return clsArr;                
            }
            function checkifallunchecked(){
                var response = true;
                var checkboxes = document.querySelectorAll("input[type=checkbox]");
                checkboxes.forEach(function(checkbox) {
                    if (checkbox.checked) {
                        response = false;
                    }
                })
                return response;
            }     
            function countResults(){
                var i=0;
                document.querySelectorAll('table').forEach(function(val){
                    if(val.style.display=='block'){
                        i = i+1;
                    }
                })
                return i;
            }
        </script>
    {% else %}
        <tr>
            <td>{{message}}</td>
        </tr>
    {% endif %}
</div>

{% endblock %}